import { h } from 'hastscript'
import { toHtml } from 'hast-util-to-html'

const DATABASE = 'github-stars.duckdb'

async function queryDuckdb<T>(database: string, sql: string): Promise<T[]> {
  const proc = Bun.spawn(['duckdb', '-json', '-no-stdin', database, sql])
  return await new Response(proc.stdout).json()
}

const getLanguages = () => queryDuckdb<{ primary_language: string }>(DATABASE, `
SELECT
  primary_language
FROM
  total_stars_by_language
WHERE
  primary_language IS NOT NULL
ORDER BY
  stargazers DESC
`)

async function generateReadme(filename: string) {
  const file = Bun.file(filename);
  const writer = file.writer();

  writer.write(`
![Number of stargazers by language](./generated/star-history.svg)

The above chart is generated by [yastar](https://github.com/akirak/yastar).
`)

  for (const { primary_language: language } of await getLanguages()) {
    writer.write('\n\n' + toHtml(h('details', [
      h('summary', [language])
    ])))
  }

  writer.end();
}

generateReadme('README.md')
