async function generateReadme(filename: string) {
  const file = Bun.file(filename)
  await Bun.write(file, `
![Number of stargazers by language](./generated/star-history.svg)

The above chart is generated by [yastar](https://github.com/akirak/yastar).
`)
}

generateReadme('README.md')
