name: Lint the npm package

on:
  pull_request:
    paths:
      - '*.ts'
      - 'bun.lockb'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install 

      - name: Run eslint
        run: bun run eslint
