name: Update the star history
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # needed by git-auto-commit-action
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            accept-flake-config = true

      - name: Restore the database
        id: database
        uses: actions/cache@v4
        with:
          path: github-stars.duckdb
          key: github-stars-database

      - name: Generate the chart
        run: nix run .#update-chart
        env:
          DUCKDB_DATABASE: github-stars.duckdb
          GITHUB_API_TOKEN: ${{ secrets.PAT }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Update the star history chart'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
