name: Update readme
on:
  pull_request:
    paths:
      - '*.ts'
  push:
    branches:
      - master
    paths:
      - '*.ts'
  workflow_dispatch:
  schedule:
    - cron: '50 4 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # needed by git-auto-commit-action
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            accept-flake-config = true

      - name: Update the readme
        run: nix run .#update-readme

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Update readme'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
